- name: Set timezone to Asia/Ho_Chi_Minh
  ansible.builtin.file:
      src: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
      dest: /etc/localtime
      state: link
      force: true
  notify: Update timezone

- name: Install basic packages
  ansible.builtin.apt:
      name:
          - python3-pip
          - htop
          - tmux
          - git
          - curl
          - locales
      update_cache: false

- name: Generate locales
  community.general.locale_gen:
      name: en_US.UTF-8
      state: present

- name: Place .bashrc to root
  ansible.builtin.copy:
      src: .bashrc
      dest: /root/.bashrc
      mode: "0644"
