services:
  app:
    privileged: true
    restart: unless-stopped
    build: .
    pids_limit: 256
    mem_limit: 256M
    cpus: 0.5
    ports:
      - "5501:5501"
    volumes:
      - volume:/srv/tmp
    depends_on:
      - cleaner
  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    volumes:
      - volume:/data
    cpus: 0.2
    mem_limit: 64M
    environment:
      - DELETE_AFTER=30m
      - SLEEP=10m
      - DIRS=/data

volumes:
  volume:
