---
- name: Install Open vSwitch
  ansible.builtin.apt:
    name: openvswitch-switch

- name: Replace IP
  ansible.builtin.template:
    src: "./10-enp8s0.yaml.j2"
    dest: "/etc/netplan/10-enp8s0.yaml"
    owner: root
    mode: "0600"
  vars:
    tip: "{{ inventory_hostname.split('-')[1] | lower }}"
    fip: "2"

- name: Apply new IP
  ansible.builtin.command:
    cmd: netplan apply
    creates: /etc/netplan/something.yml

- name: Change Ubuntu password
  ansible.builtin.shell:
    cmd: echo -n "ubuntu:R00tP@ss" | chpasswd

- name: Upload SSH Public Key
  ansible.builtin.copy:
    src: "./team{{ inventory_hostname.split('-')[1] | lower }}_id_ed25519.pub"
    dest: "/home/ubuntu/.ssh/authorized_keys"
    owner: ubuntu
    group: ubuntu
    mode: "0600"
