services:
  crypto1:
    restart: unless-stopped
    build: .
    pids_limit: 256
    mem_limit: 64M
    cpus: 0.5
    ports:
      - "10000:10000"
    volumes:
      - ./notes:/app/notes
    environment:
      - FLASK_ENV=development
    
  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    pids_limit: 128
    mem_limit: 128M
    cpus: 0.25
    volumes:
      - "./notes:/notes"
    environment:
      - DELETE_AFTER=30m
      - SLEEP=30m
      - DIRS=/notes