---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - iptables
      - iptables-persistent
    state: present

- name: Stop Wireguard server
  ansible.builtin.systemd:
    name: "wg-quick@game"
    state: stopped

- name: Upload VPN server
  ansible.builtin.copy:
    src: "./out/server.conf"
    dest: "/etc/wireguard/game.conf"
    owner: root
    group: root
    mode: "0600"

- name: Start Wireguard server
  ansible.builtin.systemd:
    name: "wg-quick@game"
    state: started
    enabled: true

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: true
    reload: true

- name: Set default policies
  ansible.builtin.iptables:
    chain: "{{ item.chain }}"
    policy: "{{ item.policy }}"
    table: filter
  loop:
    - { chain: INPUT, policy: ACCEPT }
    - { chain: FORWARD, policy: DROP }
    - { chain: OUTPUT, policy: ACCEPT }

- name: Allow established connections
  ansible.builtin.iptables:
    chain: FORWARD
    table: filter
    jump: ACCEPT
    state: present
    ctstate: ESTABLISHED,RELATED

- name: Forward from 10.10.10.0/16 to 10.80.0.0/16
  ansible.builtin.iptables:
    chain: FORWARD
    source: 10.10.10.0/16
    destination: 10.80.0.0/16
    jump: ACCEPT
    table: filter
    state: present

- name: Forward from 10.60.0.0/16 to 10.80.0.0/16
  ansible.builtin.iptables:
    chain: FORWARD
    source: 10.60.0.0/16
    destination: 10.80.0.0/16
    jump: ACCEPT
    table: filter
    state: present

- name: Forward from 10.80.0.0/16 to 10.10.10.0/16
  ansible.builtin.iptables:
    chain: FORWARD
    source: 10.80.0.0/16
    destination: 10.10.10.0/16
    jump: ACCEPT
    table: filter
    state: present

- name: Setup NAT masquerading
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
    state: present

- name: Change ips # noqa: command-instead-of-module, no-changed-when
  ansible.builtin.shell:
    cmd: |
      sed -E -i 's/10\.80\.[0-9]+\.[0-9]+/10.80.0.5/' /etc/netplan/50-cloud-init.yaml
      sed -E -i 's/10\.10\.[0-9]+\.[0-9]+/10.10.10.10/' /etc/netplan/50-cloud-init.yaml
      netplan apply
    executable: /bin/bash
