---
- name: Install Open vSwitch
  ansible.builtin.apt:
    name: openvswitch-switch

- name: Install require python packages
  ansible.builtin.pip:
    name:
      - requests
      - PyYAML
      - click
      - pydantic

- name: Upload install Docker script
  ansible.builtin.copy:
    src: "./install_docker.sh"
    dest: "/tmp/install_docker.sh"
    owner: root
    group: root
    mode: "0755"

- name: Install Docker
  ansible.builtin.command:
    cmd: "/tmp/install_docker.sh"
    creates: "/tmp/docker_marker"

- name: Upload start router script
  ansible.builtin.copy:
    src: "./start_router.sh"
    dest: "/etc/networkd-dispatcher/routable.d/50-static-router"
    owner: root
    group: root
    mode: "0644"

- name: Upload Netplan configuration
  ansible.builtin.copy:
    src: "./10-enp8s0.yaml"
    dest: "/etc/netplan/10-enp8s0.yaml"
    owner: root
    group: root
    mode: "0600"

- name: Apply Netplan configuration
  ansible.builtin.command:
    cmd: netplan apply

- name: Upload folder ForcAD
  ansible.builtin.copy:
    src: "./ForcAD"
    dest: "/root"
    owner: root
    group: root
    mode: "0744"

- name: Link control
  ansible.builtin.file:
    src: "/root/ForcAD/control.sh"
    dest: "/usr/local/bin/control"
    owner: root
    group: root
    mode: "0755"
    state: link
