---
- name: Close Network
  hosts: vpn-machine
  tags: close
  become: true
  gather_facts: false
  tasks:
    - name: Allow connection from team to vulnbox
      community.general.ufw:
        from_ip: "10.{{ 60 + (item + 1) // 256 }}.{{ (item + 1) % 256 }}.0/24"
        to_ip: "10.{{ 80 + (item + 1) // 256 }}.{{ (item + 1) % 256 }}.0/24"
        proto: any
        rule: allow
        route: true
        insert: 2
      loop: "{{ range(2) | list }}"

    - name: Deny connetion from team to other vulnbox
      community.general.ufw:
        from_ip: "10.60.0.0/16"
        to_ip: "10.80.0.0/16"
        proto: any
        rule: deny
        route: true

    - name: Deny connection between vulnboxes
      community.general.ufw:
        from_ip: "10.80.0.0/16"
        to_ip: "10.80.0.0/16"
        proto: any
        rule: deny
        route: true

- name: Open Network
  hosts: vpn-machine
  tags: open
  become: true
  gather_facts: false
  tasks:
    - name: Allow connection between vulnboxes
      community.general.ufw:
        from_ip: "10.80.0.0/16"
        to_ip: "10.80.0.0/16"
        proto: any
        rule: allow
        route: true

    - name: Allow connetion from team to other vulnbox
      community.general.ufw:
        from_ip: "10.60.0.0/16"
        to_ip: "10.80.0.0/16"
        proto: any
        rule: allow
        route: true

    - name: Allow connection from team to vulnbox
      community.general.ufw:
        from_ip: "10.{{ 60 + (item + 1) // 256 }}.{{ (item + 1) % 256 }}.0/24"
        to_ip: "10.{{ 80 + (item + 1) // 256 }}.{{ (item + 1) % 256 }}.0/24"
        proto: any
        rule: allow
        route: true
        delete: true
      loop: "{{ range(2) | list }}"

- name: Limit team
  hosts: vpn-machine
  tags: limit
  become: true
  gather_facts: false
  tasks:
    - name: Limit team
      community.general.ufw:
        from_ip: "10.{{ 60 + team | int // 256 }}.{{ team | int % 256 }}.0/24"
        to_ip: "10.0.0.0/8"
        proto: any
        rule: limit
        route: true
        insert: 1

- name: Unlimit team
  hosts: vpn-machine
  tags: unlimit
  become: true
  gather_facts: false
  tasks:
    - name: Unlimit team
      community.general.ufw:
        from_ip: "10.{{ 60 + team | int // 256 }}.{{ team | int % 256 }}.0/24"
        to_ip: "10.0.0.0/8"
        proto: any
        rule: limit
        route: true
        delete: true
