version: "3.8"

x-db-env: &db-env
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secretPassw0rd}
  MYSQL_DATABASE: ${MYSQL_DATABASE:-labs}
  MYSQL_USER: ${MYSQL_USER:-goldTrigger}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD:-goldDigger}

services:
  labs:
    depends_on:
      - db
    links:
      - "db:database"
    restart: unless-stopped
    build: ./src
    environment:
      PORT: 9993
      <<: *db-env
    ports:
      - 9993:9993
    pids_limit: 256
    mem_limit: 400M
    cpus: 0.5

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      <<: *db-env
    volumes:
      - data:/var/lib/mysql
    pids_limit: 256
    mem_limit: 400M
    cpus: 0.5

volumes:
  data:
