game:
  mode: classic
  round_time: 20
  start_time: 2024-11-06 21:00:00
  timezone: Asia/Ho_Chi_Minh

  default_score: 2500
  flag_lifetime: 5
  game_hardness: 10.0
  inflation: true

tasks:
  - checker: pwn1/checker.py
    checker_timeout: 5
    checker_type: gevent_pfr
    gets: 1
    name: pwn1
    places: 1
    puts: 1
  - checker: web3/checker.py
    checker_timeout: 5
    checker_type: gevent_pfr
    gets: 1
    name: web3
    places: 1
    puts: 1
  - checker: crypto3/checker.py
    checker_timeout: 5
    checker_type: gevent_pfr
    gets: 1
    name: crypto3
    places: 1
    puts: 1
  - checker: pwn2/checker.py
    checker_timeout: 5
    checker_type: gevent_pfr
    gets: 1
    name: pwn2
    places: 1
    puts: 1
  - checker: crypto1/checker.py
    checker_timeout: 15
    checker_type: gevent_pfr
    gets: 1
    name: crypto1
    places: 1
    puts: 1
  - checker: web2/checker.py
    checker_timeout: 5
    checker_type: gevent_pfr
    gets: 1
    name: web2
    places: 2
    puts: 1
  - checker: web1/checker.py
    checker_timeout: 20
    checker_type: gevent_pfr
    gets: 1
    name: web1
    places: 3
    puts: 1
  - checker: crypto2/checker.py
    checker_timeout: 20
    checker_type: gevent_pfr
    gets: 1
    name: crypto2
    places: 1
    puts: 1

teams:
  - ip: 10.80.1.1
    name: team 1

  - ip: 10.80.1.2
    name: team 2

  - ip: 10.80.1.3
    name: team 3
